agent:
  clientId: "${WIZ_OUTPOST_CLIENT_ID}"
  clientSecret: "${WIZ_OUTPOST_CLIENT_SECRET}"
  outpostId: "${WIZ_OUTPOST_ID}"
imagePullSecrets:
- name: wiz-outpost-lite-image-pull
runners:
  rem-aws-ebs-007:
    enabled: true
