agent:
  clientId: "${WIZ_OUTPOST_CLIENT_ID}"
  clientSecret: "${WIZ_OUTPOST_CLIENT_SECRET}"
  outpostId: "${WIZ_OUTPOST_ID}"
imagePullSecrets:
- name: wiz-outpost-lite-image-pull
runners:
  rem-custom-0009:
    enabled: true
  rem-custom-0010:
    enabled: true
  rem-custom-0011:
    enabled: true
