agent:
  clientId: "${WIZ_OUTPOST_CLIENT_ID}"
  clientSecret: "${WIZ_OUTPOST_CLIENT_SECRET}"
  outpostId: "${WIZ_OUTPOST_ID}"
imagePullSecrets:
- name: wiz-outpost-lite-image-pull
runners:
  rem-aws-ebs-007:
    enabled: true
  rem-aws-ec2-031:
    enabled: true
  rem-aws-iam-025:
    enabled: true
  rem-aws-iam-045:
    enabled: true
  rem-aws-iam-223:
    enabled: true
  rem-aws-rds-002:
    enabled: true
  rem-aws-rds-003:
    enabled: true
  rem-aws-s3-046:
    enabled: true
